@isTest
public class ZeniaGraphRestApiLeadTest {
    /*static testMethod void testGraphRestApiLead(){
        
       ID ldids ;
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/api/lead';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response= res;
        Map<String,Object> requestData = (Map<String,Object>) JSON.deserializeUntyped('{"company": "Apple","industry": "Banking","status": "Active","datasource":"Linkedin","lastName": "Test","sicCode": "2345678","niacCode": "12345"}');
        Map<String,String> result = zeniaGraphRestApiLead.createLead();
        //JSONParser parser  = JSON.createParser('{"company": "Apple","industry": "Banking","status": "Active","datasource":"Linkedin","lastName": "Test","sicCode": "2345678","niacCode": "12345"}');
        String resultData = result.get('status');
        
        system.debug('status is'+ resultData);
        system.assertEquals('Success', resultData);
            
        
    }*/


}